version: "3"
services: 
    myapp1:
      image: xyz:v2
      container_name: uvv2
      ports:
        - "8080:80"
    myapp2:
      image: centos:7
      container_name: ashish2
      ports:
        - "8081:80"
    myapp3:
      image: httpd
      container_name: mittal2
      ports:
        - "8082:80"
    myapp4:
     image: nginx
     container_name: agarwal2
     ports:
       - "8083:80"
     volumes:
      - ./webdata:/var/www/html/
